### ISSUE TITLE
Can't use the command after some setup steps

### ISSUE THREAD

**Issue by olivergierke** [0x6368/LIFred#4]
I've used the configuration command to try to disable some of the suggestions shown for the lifred command (scenes etc.). Now when I am trying to use the bulbs using the lifred command I get a fatal error notice with this appearing in the logs:

```
E, [2016-12-15 12:11:17 #91083] ERROR -- de.bieg-software.LIFred: A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<NoMethodError: undefined method `each' for nil:NilClass>
  ./lifx_script_filter.rb:136:in `block in <main>'  
/Users/olivergierke/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3A3CCE3F-8959-4A65-A3FB-970286C74559/bundle/ruby/2.0.0/gems/alfred-workflow-2.0.5/lib/alfred.rb:82:in `with_friendly_error'  
./lifx_script_filter.rb:15:in `<main>'
```

Have you seen this before? Is there an easy way to basically wipe my setup and start from scratch? I revoked my API key and created a new one. The resetup seems to work but the error message persists.

**Comment by olivergierke** [comment]
I can get things to work again by enabling the scenes to show up again. Configuring them to be hidden then causes the error again. Looks like I am running into the issue fixed by 7a9c2a27f2467d63a4b93c40ffa67f63600e0d1b (applying the change locally solves the issue for me).

Care to craft a new release for Packal?

**Comment by 0x6368** [comment]
Sorry, I don't have any LIFX bulbs any more, so it is quite hard to check for issues. I updated the Alfred Workflow on Packal and here to include the fix https://github.com/0x6368/LIFred/commit/7a9c2a27f2467d63a4b93c40ffa67f63600e0d1b.

**Comment by olivergierke** [comment]
Thanks for the quick turnaround! :)
