### ISSUE TITLE
Stopped working on macOS 10.13 High Sierra

### ISSUE THREAD

**Issue by eidermar** [0x6368/LIFred#6]
Hello!

I'm referencing this closed issue: #5

I'm having the exact same problem. Now that High Sierra is released maybe you could take another look at this.

I read something about bundeling ruby gems with the worklflow should solve the problem but don't really have an idea what that would mean exactly.

Thank you!

**Comment by nivshah** [comment]
Having this issue as well. Seems like it is similar to what you noticed in #5 

```Starting debug for 'LIFred'

[2017-11-13 17:21:02][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- alfred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./lifx_script_filter.rb:10:in `<main>'```

**Comment by nivshah** [comment]
I was able to resolve this using the following steps:

1) Install/Update XCode, which I hadn't opened after updating to High Sierra
2) Manually install a couple of gems (`alfred-workflow`,`curb`)

LIFred works fine for me again. Hooray!

**Comment by 0x6368** [comment]
Thank you for the report! I am kind of busy right now, but I will look into these issues until the end of the week. A temporary fix should be to install some gems manually (like @nivshah already mentioned).

**Comment by 0x6368** [comment]
I fixed this issue and just released an update: https://github.com/0x6368/LIFred/releases/latest

**Comment by nivshah** [comment]
Got a chance to use the new release - Downloaded the .workflow file and clicked it and chose to migrate

```[2017-11-28 17:54:06][ERROR: action.script] /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/niv/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5AEB2BFE-A970-4464-8B14-D1953D6885A0/bundle/ruby/2.3.0/gems/curb-0.9.4/ext/curb_core.bundle, 9): Library not loaded: /Users/christianbieg/.rvm/rubies/ruby-2.3.0/lib/libruby.2.3.0.dylib (LoadError)
  Referenced from: /Users/niv/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5AEB2BFE-A970-4464-8B14-D1953D6885A0/bundle/ruby/2.3.0/gems/curb-0.9.4/ext/curb_core.bundle
  Reason: image not found - /Users/niv/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5AEB2BFE-A970-4464-8B14-D1953D6885A0/bundle/ruby/2.3.0/gems/curb-0.9.4/ext/curb_core.bundle
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/niv/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5AEB2BFE-A970-4464-8B14-D1953D6885A0/bundle/ruby/2.3.0/gems/curb-0.9.4/lib/curl.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/niv/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5AEB2BFE-A970-4464-8B14-D1953D6885A0/bundle/ruby/2.3.0/gems/curb-0.9.4/lib/curb.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./lifx_run_script.rb:12:in `<main>'```

Something seems amiss with the pathnames? I don't know enough about what is going on to speculate more than that.

**Comment by 0x6368** [comment]
Sorry, my ruby installation is pretty messed up.

**Comment by nivshah** [comment]
Yep this version works great!

**Comment by 0x6368** [comment]
Great! I uploaded the new version. It should install itself (after 7 days max) if you try to use Version 1.03.
